apiVersion: v1
kind: Secret
metadata:
  name: orion-platform-secret
type: Opaque
stringData:
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
  RABBITMQ_PASSWORD: "guest"
  REDIS_PASSWORD: ""
  DB_PASSWORD: "postgres"
